version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashflow-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    # Exemplo de variáveis de ambiente (se necessário)
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - REACT_APP_USE_MOCKS=false
    networks:
      - cashflow-network
    # Exemplo de healthcheck (opcional)
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s



networks:
  cashflow-network:
    driver: bridge

